version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: mainuser
      POSTGRES_PASSWORD: 123456789
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: