services:
  backend:
    build:
      context: ./Back_end
      dockerfile: Dockerfile.dev
    volumes:
      - ./Back_end:/app
      - ./Back_end/staticfiles_collected:/app/staticfiles_collected
    expose:
      - "8000:8000"
    env_file:
      - .env
    command: gunicorn project.wsgi:application --bind 0.0.0.0:8000 --reload