# Generated by Django 5.2.2 on 2025-06-11 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoVisualizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progresso_segundos', models.PositiveIntegerField(default=0)),
                ('ultima_visualizacao_em', models.DateTimeField(auto_now=True)),
                ('concluido', models.BooleanField(default=False)),
                ('data_inicio_visualizacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Histórico de Visualização',
                'verbose_name_plural': 'Históricos de Visualização',
                'ordering': ['-ultima_visualizacao_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemListaInteresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('data_adicao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-data_adicao'],
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comentario_texto', models.TextField(blank=True, null=True)),
                ('data_avaliacao', models.DateTimeField(auto_now_add=True)),
                ('filme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_recebidas', to='media.filme')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
                'ordering': ['-data_avaliacao'],
            },
        ),
    ]
