# Generated by Django 5.2.2 on 2025-06-11 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('interactions', '0001_initial'),
        ('media', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='perfil_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_feitas', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_recebidas', to='media.serie'),
        ),
        migrations.AddField(
            model_name='historicovisualizacao',
            name='episodio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visualizacoes_historico', to='media.episodio'),
        ),
        migrations.AddField(
            model_name='historicovisualizacao',
            name='filme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visualizacoes_historico', to='media.filme'),
        ),
        migrations.AddField(
            model_name='historicovisualizacao',
            name='perfil_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_visualizacao', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='itemlistainteresse',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='itemlistainteresse',
            name='perfil_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_lista_interesse', to='users.userprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='itemlistainteresse',
            unique_together={('perfil_usuario', 'content_type', 'object_id')},
        ),
    ]
