# Generated by Django 5.2.2 on 2025-06-25 03:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conteudo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoritoFilme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritado_por', to='conteudo.filme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos_filmes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favorito Filme',
                'verbose_name_plural': 'Favoritos Filmes',
                'unique_together': {('user', 'filme')},
            },
        ),
        migrations.CreateModel(
            name='FavoritoSerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritado_por', to='conteudo.serie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos_series', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favorito Série',
                'verbose_name_plural': 'Favoritos Séries',
                'unique_together': {('user', 'serie')},
            },
        ),
    ]
