# Generated by Django 5.2.2 on 2025-06-11 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('biografia', models.TextField(blank=True, null=True)),
                ('foto_url', models.URLField(blank=True, max_length=500, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Pessoas',
                'ordering': ['nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('sinopse', models.TextField()),
                ('ano_lancamento', models.PositiveIntegerField()),
                ('imagem_poster_url', models.URLField(blank=True, max_length=500, null=True)),
                ('classificacao_indicativa', models.CharField(blank=True, max_length=10, null=True)),
                ('data_adicao', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(help_text='Identificador único para URLs amigáveis', max_length=255, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('duracao_minutos', models.PositiveIntegerField(help_text='Duração do filme em minutos')),
                ('arquivo_video_url', models.URLField(help_text='URL do arquivo de vídeo do filme', max_length=1000)),
                ('generos', models.ManyToManyField(blank=True, related_name='filmes', to='media.genero')),
            ],
            options={
                'ordering': ['-data_adicao'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('sinopse', models.TextField()),
                ('ano_lancamento', models.PositiveIntegerField()),
                ('imagem_poster_url', models.URLField(blank=True, max_length=500, null=True)),
                ('classificacao_indicativa', models.CharField(blank=True, max_length=10, null=True)),
                ('data_adicao', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(help_text='Identificador único para URLs amigáveis', max_length=255, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('status', models.CharField(blank=True, choices=[('EM_ANDAMENTO', 'Em Andamento'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='EM_ANDAMENTO', max_length=20, null=True)),
                ('generos', models.ManyToManyField(blank=True, related_name='series', to='media.genero')),
            ],
            options={
                'ordering': ['-data_adicao'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CreditoMidia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_credito', models.CharField(choices=[('ATOR', 'Ator/Atriz'), ('DIRETOR', 'Diretor(a)'), ('ROTEIRISTA', 'Roteirista'), ('PRODUTOR', 'Produtor(a)')], max_length=50)),
                ('personagem_nome', models.CharField(blank=True, max_length=150, null=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('filme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creditos_filme', to='media.filme')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditos', to='media.pessoa')),
                ('serie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creditos_serie', to='media.serie')),
            ],
            options={
                'ordering': ['ordem', 'pessoa__nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_temporada', models.PositiveIntegerField()),
                ('titulo', models.CharField(blank=True, max_length=255, null=True)),
                ('ano_lancamento', models.PositiveIntegerField(blank=True, null=True)),
                ('imagem_poster_url', models.URLField(blank=True, max_length=500, null=True)),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporadas', to='media.serie')),
            ],
            options={
                'ordering': ['serie', 'numero_temporada'],
                'unique_together': {('serie', 'numero_temporada')},
            },
        ),
        migrations.CreateModel(
            name='Episodio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_episodio', models.PositiveIntegerField()),
                ('titulo', models.CharField(max_length=255)),
                ('sinopse', models.TextField(blank=True, null=True)),
                ('duracao_minutos', models.PositiveIntegerField()),
                ('arquivo_video_url', models.URLField(max_length=1000)),
                ('data_lancamento_original', models.DateField(blank=True, null=True)),
                ('imagem_thumbnail_url', models.URLField(blank=True, max_length=500, null=True)),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodios', to='media.temporada')),
            ],
            options={
                'ordering': ['temporada', 'numero_episodio'],
                'unique_together': {('temporada', 'numero_episodio')},
            },
        ),
    ]
