# Generated by Django 5.2.2 on 2025-06-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssinaturaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim_periodo_corrente', models.DateTimeField()),
                ('status_assinatura', models.CharField(choices=[('ATIVA', 'Ativa'), ('CANCELADA', 'Cancelada'), ('PENDENTE_PAGAMENTO', 'Pendente Pagamento'), ('EXPIRADA', 'Expirada'), ('AVALIACAO_GRATUITA', 'Avaliação Gratuita'), ('INADIMPLENTE', 'Inadimplente')], db_index=True, default='PENDENTE_PAGAMENTO', max_length=25)),
                ('data_cancelamento', models.DateTimeField(blank=True, null=True)),
                ('cancelada_no_fim_periodo', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Assinatura de Usuário',
                'verbose_name_plural': 'Assinaturas de Usuários',
            },
        ),
        migrations.CreateModel(
            name='PlanoAssinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_plano', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('preco_mensal', models.DecimalField(decimal_places=2, max_digits=6)),
                ('preco_anual', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('qualidade_video_permitida', models.CharField(choices=[('SD', 'Definição Padrão (SD)'), ('HD', 'Alta Definição (HD - 720p/1080p)'), ('4K', 'Ultra Alta Definição (4K+HDR)')], default='HD', max_length=20)),
                ('numero_telas_simultaneas', models.PositiveSmallIntegerField(default=1)),
                ('ativo', models.BooleanField(default=True)),
                ('stripe_price_id_mensal', models.CharField(blank=True, max_length=100, null=True)),
                ('stripe_price_id_anual', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Plano de Assinatura',
                'verbose_name_plural': 'Planos de Assinatura',
                'ordering': ['preco_mensal'],
            },
        ),
    ]
